name: 'buf-push'
description: >
  Push buf module updates to the Buf Schema Registry.
branding:
  icon: arrow-up
  color: blue
inputs:
  buf_token:
    description: 'The buf authentication token.'
    required: true
  input:
    description: 'The input path.'
    default: '.'
    required: false
runs:
  using: composite
  steps:
    - name: set path
      shell: bash
      env:
        CACHE: ${{ runner.temp }}/${{ github.action }}
      run: echo "${CACHE}/bin" >> "${GITHUB_PATH}"
    - name: install yq
      shell: bash
      env:
        CACHE: ${{ runner.temp }}/${{ github.action }}
      run: make yq
    - run: yq --help
      shell: bash
    - name: push
      shell: bash
      env:
        BUF_TOKEN: ${{ inputs.buf_token }}
      run: ./push.bash ${{ inputs.input }}
