name: buf-push
description: >
  Push buf module updates to the Buf Schema Registry.
branding:
  icon: arrow-up
  color: blue
inputs:
  buf_token:
    description: The Buf authentication token.
    required: true
  input:
    description: The Input path.
    default: '.'
    required: false
  draft:
    description: The identifier of enabling draft, when set to 'true' the action will push the module as draft if the branch that trigger the workflow is not 'main'.
    required: false
runs:
  using: composite
  steps:
    - name: push
      shell: bash
      env:
        BUF_TOKEN: ${{ inputs.buf_token }}
        DRAFT: ${{ inputs.draft }}
      run: $GITHUB_ACTION_PATH/push.bash ${{ inputs.input }}
