name: buf-push
description: >
  Push buf module updates to the Buf Schema Registry.
branding:
  icon: arrow-up
  color: blue
inputs:
  buf_token:
    description: The Buf authentication token.
    required: true
  input:
    description: The Input path.
    default: '.'
    required: false
  default_branch:
    description: The git branch that gets pushed to the main track on BSR.
    default: main
    required: false
  track:
    description: The track to push to.
    default: ${{ github.ref_name }}
    required: false
  github_token:
    description: The Github authentication token.
    required: false
    default: ${{ github.token }}
outputs:
  commit:
    description: The commit pushed to the Buf Schema Registry.
  commit_url:
    description: The URL to view commit on the Buf Schema Registry.
runs:
  using: docker
  #  TODO: see https://github.com/actions/jekyll-build-pages for example workflow of publishing and image instead of building from Dockerfile
  image: Dockerfile
