name: buf-push
description: >
  Push buf module updates to the Buf Schema Registry.
branding:
  icon: arrow-up
  color: blue
inputs:
  buf_token:
    description: The Buf authentication token.
    required: true
  input:
    description: The Input path.
    default: '.'
    required: false
  track:
    description: The track to push to.
    default: main
    required: false
outputs:
  commit:
    description: The commit pushed to the Buf Schema Registry.
    value: ${{ steps.push.outputs.commit }}
  commit_url:
    description: The URL to view commit on the Buf Schema Registry.
    value: ${{ steps.push.outputs.commit_url }}
runs:
  using: composite
  steps:
    - id: cache-setup
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "::set-output name=key::${RUNNER_OS}-buf-push-action-${GITHUB_ACTION_REF:-$(git rev-parse --short HEAD)}"
        echo "::set-output name=path::${RUNNER_TEMP}/buf-push-action/bin"
    - id: notice
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "::notice:: cache-key ${{ steps.cache-setup.outputs.key }}"
        echo "::notice:: cache-path ${{ steps.cache-setup.outputs.path }}"
        echo "::notice:: action_path ${{ github.action_path }}"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.cache-setup.outputs.path }}
        key: ${{ steps.cache-setup.outputs.key }}
    - name: build
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: ./downloadbinary.bash "${{ github.action_ref }}" "${{ steps.cache-setup.outputs.path }}"
    - name: push
      id: push
      shell: bash
      env:
        BUF_TOKEN: ${{ inputs.buf_token }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        "${{ steps.cache-setup.outputs.path }}/buf-push-action" "${{ inputs.input }}" "${{ inputs.track }}" "${{ github.sha }}"
