name: 'buf-push'
description: >
  Push buf module updates to the Buf Schema Registry.
branding:
  icon: arrow-up
  color: blue
inputs:
  buf_token:
    description: 'The buf authentication token.'
    required: true
  input:
    description: 'The input path.'
    default: '.'
    required: false
runs:
  using: composite
  steps:
    - name: prepare environment
      shell: bash
      env:
        CACHE: ${{ runner.temp }}/${{ github.action }}
      run: |
        echo "${CACHE}/bin" >> "${GITHUB_PATH}"
        echo "CACHE=${CACHE}" >> "${GITHUB_ENV}"
    - uses: actions/cache@v2
      with:
        path: ${{ runner.temp }}/${{ github.action }}
        key: ${{ github.action }}-${{ runner.os }}-${{ hashFiles('${{ github.action_path }}/make/**') }}-${{ hashFiles('${{ github.action_path }}/action.yml') }}
        restore-keys:
          - ${{ github.action }}-${{ runner.os }}-
    - name: install yq
      shell: bash
      run: make yq
    - shell: bash
      run: yq --help
    - name: push
      shell: bash
      env:
        BUF_TOKEN: ${{ inputs.buf_token }}
      run: ./push.bash ${{ inputs.input }}
