name: buf-push
description: >
  Push buf module updates to the Buf Schema Registry.
branding:
  icon: arrow-up
  color: blue
inputs:
  buf_token:
    description: The Buf authentication token.
    required: true
  input:
    description: The Input path.
    default: '.'
    required: false
runs:
  using: composite
  steps:
    - name: push
      shell: bash
      env:
        BUF_TOKEN: ${{ inputs.buf_token }}
      run: ./push.bash ${{ inputs.input }}
