name: buf-push
description: >
  Push Buf module updates to the Buf Schema Registry.
branding:
  icon: arrow-up
  color: blue
inputs:
  buf_token:
    description: The Buf authentication token.
    required: true
  input:
    description: The Buf input path.
    default: '.'
    required: false
  track:
    description: The track to push to.
    default: main
    required: false
runs:
  using: composite
  steps:
    - name: push
      shell: bash
      env:
        BUF_TOKEN: ${{ inputs.buf_token }}
      run: $GITHUB_ACTION_PATH/push.bash "${{ inputs.input }}" "${{ inputs.track }}"
